name: unit test
on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: UnitTest
      run: python Unittest.py