name: interation test
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: IntegrationTest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: UnitTest
      run: python Unittest.py
    - name: IntegrationTest
      run: python Integrationtest.py